configuration:
  projectName: service-core
server:
  url: http://localhost:8070/rest/api
  port: 8070
  paasCallbackTimeoutMillsTime: 180000
access:
  server:
    url: ws://172.16.2.144:7099
    ip: 172.16.2.144
    port: 7099
core:
  quartz:
    notifyWaitInterval: 60
    applyScheduleInterval: 5
    maxPopCount: 1
    linkedDisconnectTimeout: 60000
paas:
  server:
    url: http://172.16.2.84:9080/rest/api
    apply: com.haima.cloudplayer.controller.instance.apply
    release: com.haima.cloudplayer.controller.instance.release
    paramRelease: com.haima.cloudplayer.controller.instance.releaseNew
    refresh: com.haima.cloudplayer.controller.instance.refreshSToken
    resolution: com.haima.cloudplayer.controller.instance.updateResolution
    router: com.haima.cloudplayer.controller.router.getInterface
    hotfix: com.haima.cloudplayer.controller.package.resource.upload
    testUrl: http://172.16.2.84:9080/rest/api
    formUrl: http://172.16.2.84:9080/rest/api
boss:
  server:
    #url: http://120.26.4.141:8586/rest/api/app/sass/callback
    url: http://172.16.89.19:8080/rest/api/app/sass/callback
spring:
  redis:
    host: dev-redis
    port: 6379
    password: 123qwe
    database: 1
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: 200
haima:
  datasource:
    service-core:
      host: dev-mysql
      port: 3306
      database: db_service_core
      properties:
        driverClassName: com.mysql.jdbc.Driver
        username: admin
        password: 123qwe
        url: jdbc:mysql://dev-mysql:3306/db_service_core?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
        validationQuery: SELECT 1
        validationInterval: 30000
        testOnBorrow: true
  rabbit:
    receiver:
      enable: true
    receivers:
    - queue: queue.cloudservice.channel.statemachine
    - queue: queue.valueadded.verify.result
    - queue: queue.msgcenter.clientstate.canceled
    - queue: queue.linkserver.clientstate.connectfailed
    - queue: queue.msgcenter.clientstate.ready
  screen:
    termInfo:
      android:
        dpi: 320
        resolution: 1920x1080
      web:
        dpi: 320
        resolution: 1920x1080
      pc:
        dpi: -1
        resolution: -1x-1
      mac:
        dpi: -1
        resolution: -1x-1
    iosInfo:
      iPhone2G:
        dpi: 163
        resolution: 320x480
      iPhone3G:
        dpi: 163
        resolution: 320x480
      iPhone3GS:
        dpi: 163
        resolution: 320x480
      iPhone4:
        dpi: 326
        resolution: 640x960
      iPhone4S:
        dpi: 326
        resolution: 640x960
      iPhone5:
        dpi: 326
        resolution: 640x1136
      iPhone5c:
        dpi: 326
        resolution: 640x1136
      iPhone5s:
        dpi: 326
        resolution: 640x1136
      iPhone6:
        dpi: 326
        resolution: 750x1334
      iPhone6Plus:
        dpi: 401
        resolution: 1080x1920
      iPhone6s:
        dpi: 326
        resolution: 750x1334
      iPhoneSE:
        dpi: 326
        resolution: 640x1136
      iPhone7:
        dpi: 326
        resolution: 750x1334
      iPhone7Plus:
        dpi: 401
        resolution: 1080x1920
      iPodTouch:
        dpi: 326
        resolution: 640x1136
      iPodTouch2G:
        dpi: 326
        resolution: 640x1136
      iPodTouch3G:
        dpi: 326
        resolution: 640x1136
      iPodTouch4G:
        dpi: 326
        resolution: 640x1136
      iPodTouch5G:
        dpi: 326
        resolution: 640x1136
      iPodTouch6G:
        dpi: 326
        resolution: 640x1136
      iPad:
        dpi: 132
        resolution: 1024x768
      iPad2:
        dpi: 132
        resolution: 1024x768
      iPad3:
        dpi: 264
        resolution: 2048x1536
      iPad4:
        dpi: 264
        resolution: 2048x1536
      iPadAir:
        dpi: 264
        resolution: 2048x1536
      iPadAir2:
        dpi: 264
        resolution: 2048x1536
      iPadmini1G:
        dpi: 163
        resolution: 1024x768
      iPadmini2:
        dpi: 163
        resolution: 1024x768
      iPadmini3:
        dpi: 163
        resolution: 1024x768
      iPadmini4:
        dpi: 163
        resolution: 1024x768
org:
  quartz:
    scheduler:
      instanceName: saas.quartz.global
      instanceId: AUTO
    threadPool:
      class: org.quartz.simpl.SimpleThreadPool
      threadCount: 5
    jobStore:
      misfireThreshold: 60000
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      dataSource: Qrtz
      tablePrefix: QRTZ_
      isClustered: true
      clusterCheckinInterval: 20000
    dataSource:
      Qrtz:
        driver: com.mysql.jdbc.Driver
        URL: jdbc:mysql://dev-mysql:3306/db_service_core_quartz?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
        user: admin
        password: 123qwe
  validationQuery: select 1
native360:
  freeLanding:
    bizType: 1
    method: synUserInfo
    appId: 0f577e0b550ad66a066dfe7a84b8162d
    aesKey: 16o1xl8dIrYjTOaB