configuration:
  projectName: tenant-mgt
server:
  port: 8090
spring:
  redis:
    host: dev-redis
    port: 6379
    password: 123qwe
    database: 1
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: 200
haima:
  datasource:
    tenant-mgt:
      host: dev-mysql
      port: 3306
      database: db_tenant_mgt
      properties:
        driverClassName: com.mysql.jdbc.Driver
        username: admin
        password: 123qwe
        url: jdbc:mysql://dev-mysql:3306/db_tenant_mgt?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
        validationQuery: SELECT 1
        validationInterval: 30000
        testOnBorrow: true
  mongo:
    tenant-mgt:
      host: dev-mongo
      port: 27017
      database: db_tenant_mgt
      username: admin
      password: 123qwe
  paysdkRPC:
    tenant-mgt:
      host: http://sdk-api-dev.haimawan.com/user_server/from_server
      appId: cb6a65e12721733fcac085ab78e1ce4b
      requestSourceIndex: CLOUD_SELF_HELP_HAIMAYUN
      aes128Key: 8wvu4JNclrnVYfaw
      signMd5Key: evzAJZolMVdcb1kVI81ymNbPqWByxuhS
  bigdataRPC:
    tenant-mgt:
      host: http://bigdata-search-data-test.haimawan.com/data/get
      appId: 1G4wk1RDKJjpfm49BZFsF8OedRWLOkiQ
      aes128Key: 6fyX8qBgd8Nd354P
      signMd5Key: BGK3RdDdd9eQLEOMg5iadAjFnrMg0JVo
  cosRPC:
    tenant-mgt:
      appId: 1252422369
      secretId: AKIDohpDkQ848945OGEYyV8sgOD8IZ2gdCyv
      secretKey: XLGHOg4YD2HgCtlp4Z6AAEZ6okzYIGLO
      bucketName: haimayuntest
      region: tj
  digest:
    tenant-mgt:
      signMd5Key: evzAJZolMVdcb1kVI81ymNbPqWByxuhS
  paasCall:
    tenant-mgt:
      testHost: http://172.16.2.84:8090/rest/api
      formalHost: http://172.16.2.84:8090/rest/api
      urgencyDeploy: com.haima.cloudplayer.ops.appbackend.worksheet.UrgencyDeploy
  bossCall:
    tenant-mgt:
      host: http://172.16.60.124:8080/rest/api/app/sass/callback